#Requires -Version 5.1
<#
.SYNOPSIS
    生成 D:\brain-assets 资产分布 + 增长趋势 + ext 统计报告.

.DESCRIPTION
    输出到 D:\brain\04-journal\brain-assets-stats-YYYY-MM-DD.md
    内容:
    - 一级目录: 文件数 / 总大小
    - 扩展名 top 20: 文件数 / 总大小
    - 按 mtime 的月增长 (文件数 + 大小)
    - top 10 最大单文件
    纯元数据, 0 token.
#>

[CmdletBinding()]
param(
    [string]$AssetsRoot = "D:\brain-assets",
    [string]$BrainRoot  = "D:\brain"
)

$today = Get-Date -Format "yyyy-MM-dd"
$report = Join-Path $BrainRoot "04-journal\brain-assets-stats-$today.md"

Write-Host "`n==== brain-assets 统计 $today ====" -ForegroundColor Cyan

$files = Get-ChildItem $AssetsRoot -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
    $_.FullName -notmatch '\\_migration\\'
}
Write-Host "扫描 $($files.Count) 个文件..." -ForegroundColor DarkGray

$totalSize = ($files | Measure-Object Length -Sum).Sum
$totalSizeGB = [math]::Round($totalSize / 1GB, 2)

# ============================================================
# 一级目录分布
# ============================================================
$topDirs = @{}
foreach ($f in $files) {
    $rel = $f.FullName.Substring($AssetsRoot.Length).TrimStart('\')
    $topDir = ($rel -split '[\\/]')[0]
    if (-not $topDirs.ContainsKey($topDir)) {
        $topDirs[$topDir] = @{ Count = 0; Size = 0L }
    }
    $topDirs[$topDir].Count++
    $topDirs[$topDir].Size += $f.Length
}

# ============================================================
# Ext 分布
# ============================================================
$extMap = @{}
foreach ($f in $files) {
    $ext = $f.Extension.ToLower()
    if (-not $ext) { $ext = '(no-ext)' }
    if (-not $extMap.ContainsKey($ext)) {
        $extMap[$ext] = @{ Count = 0; Size = 0L }
    }
    $extMap[$ext].Count++
    $extMap[$ext].Size += $f.Length
}

# ============================================================
# 按月增长 (基于 LastWriteTime)
# ============================================================
$monthMap = @{}
foreach ($f in $files) {
    $ym = $f.LastWriteTime.ToString('yyyy-MM')
    if (-not $monthMap.ContainsKey($ym)) {
        $monthMap[$ym] = @{ Count = 0; Size = 0L }
    }
    $monthMap[$ym].Count++
    $monthMap[$ym].Size += $f.Length
}

# ============================================================
# Top 10 最大单文件
# ============================================================
$topLarge = $files | Sort-Object Length -Descending | Select-Object -First 10

# ============================================================
# 写报告
# ============================================================
$md = [System.Collections.Generic.List[string]]::new()
$md.Add('---')
$md.Add('title: brain-assets 统计报告 ' + $today)
$md.Add('date: ' + $today)
$md.Add('tags: [stats, housekeeping, auto-generated]')
$md.Add('---')
$md.Add('')
$md.Add('# brain-assets 统计 ' + $today)
$md.Add('')
$md.Add("**总文件数**: $($files.Count) · **总大小**: $totalSizeGB GB")
$md.Add('')

$md.Add('## 一级目录分布')
$md.Add('')
$md.Add('| 目录 | 文件数 | 大小 (MB) | 占比 |')
$md.Add('|------|--------|-----------|------|')
foreach ($kv in ($topDirs.GetEnumerator() | Sort-Object { -$_.Value.Size })) {
    $sizeMb = [math]::Round($kv.Value.Size / 1MB, 1)
    $pct = if ($totalSize -gt 0) { [math]::Round(100 * $kv.Value.Size / $totalSize, 1) } else { 0 }
    $md.Add("| ``$($kv.Key)/`` | $($kv.Value.Count) | $sizeMb | $pct% |")
}
$md.Add('')

$md.Add('## 扩展名 Top 20 (按占用大小)')
$md.Add('')
$md.Add('| 扩展 | 文件数 | 大小 (MB) | 占比 |')
$md.Add('|------|--------|-----------|------|')
foreach ($kv in ($extMap.GetEnumerator() | Sort-Object { -$_.Value.Size } | Select-Object -First 20)) {
    $sizeMb = [math]::Round($kv.Value.Size / 1MB, 1)
    $pct = if ($totalSize -gt 0) { [math]::Round(100 * $kv.Value.Size / $totalSize, 1) } else { 0 }
    $md.Add("| ``$($kv.Key)`` | $($kv.Value.Count) | $sizeMb | $pct% |")
}
$md.Add('')

$md.Add('## 按月分布 (mtime)')
$md.Add('')
$md.Add('| 月份 | 文件数 | 大小 (MB) |')
$md.Add('|------|--------|-----------|')
foreach ($kv in ($monthMap.GetEnumerator() | Sort-Object Name)) {
    $sizeMb = [math]::Round($kv.Value.Size / 1MB, 1)
    $md.Add("| $($kv.Key) | $($kv.Value.Count) | $sizeMb |")
}
$md.Add('')

$md.Add('## Top 10 单文件')
$md.Add('')
$md.Add('| 大小 (MB) | 路径 |')
$md.Add('|-----------|------|')
foreach ($f in $topLarge) {
    $sizeMb = [math]::Round($f.Length / 1MB, 1)
    $md.Add("| $sizeMb | ``$($f.FullName)`` |")
}
$md.Add('')

$md.Add('---')
$md.Add('')
$md.Add('*auto-generated by `brain-asset-stats.ps1` (纯元数据, 0 token)*')

$md -join "`n" | Out-File $report -Encoding UTF8

Write-Host "`n==== 完成 ====" -ForegroundColor Green
Write-Host "  总文件: $($files.Count)"
Write-Host "  总大小: $totalSizeGB GB"
Write-Host "  一级目录: $($topDirs.Count)"
Write-Host "  月份跨度: $($monthMap.Count)"
Write-Host "`n报告: $report`n" -ForegroundColor Cyan
